#!/usr/bin/env python3
"""One-time fetch of the NOAA Oceanic Nino Index and its join to the long
snow and storage records already committed. Network (one small text file).

    python3 fetch_oni.py

Writes:
    sim-data/oni.json           monthly ONI 1950-present (NOAA CPC via PSL)
    sim-data/enso-context.json  per water year: winter ONI phase, peak SWE and
                                melt-out day at every mapped SNOTEL pillow (from
                                ../../water-system-3d/snotel-history.json, back
                                to 1980 for the oldest), peak storage at the
                                DWR reservoirs (../../water-system-3d/
                                storage-history.json), plus Spearman rank
                                correlations of ONI against each, with a
                                permutation p-value and n.

What is computed versus general knowledge
-----------------------------------------
The correlations are computed here from committed records; expect them to be
weak. That central Colorado sits on the ENSO "dipole" boundary, with the
wet-El Nino signal strongest in the southern Rockies and the wet-La Nina
signal in the northern Rockies, is general climatology (e.g. NOAA CPC
seasonal outlooks), stated as such in the UI. The ONI is NOAA's operational
ENSO index: a 3-month running mean of Nino-3.4 SST anomalies; phase
thresholds +/-0.5 C for five consecutive seasons are NOAA's definition.
"""

import json
import math
import os
import random
import sys
import urllib.request
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
W3D = os.path.join(HERE, "..", "..", "water-system-3d")
SIM = os.path.join(HERE, "sim-data")
URL = "https://psl.noaa.gov/data/correlation/oni.data"

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def fetch_oni():
    req = urllib.request.Request(URL, headers={"User-Agent": "design-storm-2026 fetch_oni"})
    with urllib.request.urlopen(req, timeout=60) as r:
        text = r.read().decode()
    rows = {}
    for line in text.splitlines()[1:]:
        parts = line.split()
        if len(parts) == 13 and parts[0].isdigit():
            vals = [float(v) for v in parts[1:]]
            rows[int(parts[0])] = [None if v <= -99 else v for v in vals]
    return rows


def winter_oni(rows, wy):
    """Mean ONI over Nov(wy-1), Dec(wy-1), Jan(wy), the season that sets the snowpack."""
    vals = []
    prev, cur = rows.get(wy - 1), rows.get(wy)
    if prev:
        vals += [prev[10], prev[11]]
    if cur:
        vals += [cur[0]]
    vals = [v for v in vals if v is not None]
    return round(sum(vals) / len(vals), 2) if len(vals) == 3 else None


def phase(oni):
    if oni is None:
        return None
    return "El Nino" if oni >= 0.5 else "La Nina" if oni <= -0.5 else "Neutral"


def rank(xs):
    order = sorted(range(len(xs)), key=lambda i: xs[i])
    r = [0.0] * len(xs)
    i = 0
    while i < len(order):
        j = i
        while j + 1 < len(order) and xs[order[j + 1]] == xs[order[i]]:
            j += 1
        for k in range(i, j + 1):
            r[order[k]] = (i + j) / 2 + 1
        i = j + 1
    return r


def pearson(x, y):
    n = len(x)
    mx, my = sum(x) / n, sum(y) / n
    cov = sum((a - mx) * (b - my) for a, b in zip(x, y))
    vx = sum((a - mx) ** 2 for a in x)
    vy = sum((b - my) ** 2 for b in y)
    return cov / math.sqrt(vx * vy) if vx > 0 and vy > 0 else 0.0


def spearman(x, y, n_perm=5000, seed=42):
    rx, ry = rank(x), rank(y)
    rho = pearson(rx, ry)
    rng = random.Random(seed)
    ry2 = ry[:]
    hits = 0
    for _ in range(n_perm):
        rng.shuffle(ry2)
        if abs(pearson(rx, ry2)) >= abs(rho):
            hits += 1
    return round(rho, 3), round((hits + 1) / (n_perm + 1), 4)


def peak_and_meltout(trace):
    vals = [(v, i) for i, v in enumerate(trace) if v is not None]
    if len(vals) < 200:
        return None, None
    peak, pi = max(vals)
    if peak <= 0:
        return None, None
    melt_out = next((i for v, i in vals if i > pi and v <= 0.1), None)
    return peak, melt_out


def main():
    rows = fetch_oni()
    years = sorted(rows)
    oni = {"_comment": "Generated by fetch_oni.py from NOAA CPC ONI (via NOAA PSL). Do not edit.",
           "source": URL, "fetched": date.today().isoformat(),
           "definition": "3-month running mean of ERSST Nino-3.4 SST anomalies (C), centred on the month; NOAA phase thresholds +/-0.5.",
           "years": {str(y): rows[y] for y in years}, "months": MONTHS}
    os.makedirs(SIM, exist_ok=True)
    with open(os.path.join(SIM, "oni.json"), "w") as fh:
        json.dump(oni, fh, separators=(",", ":"))
    print(f"ONI {years[0]}-{years[-1]}", file=sys.stderr)

    snotel = json.load(open(os.path.join(W3D, "snotel-history.json")))
    storage = json.load(open(os.path.join(W3D, "storage-history.json")))
    system = json.load(open(os.path.join(W3D, "system.json")))
    names = {p["id"].replace("sntl-", "") + ":CO:SNTL": p["name"] for p in system["points"] if p["kind"] == "snotel"}

    per_wy = {}
    stations_out = {}
    for triplet, st in snotel["stations"].items():
        peaks, melts = [], []
        for wy, trace in st["years"].items():
            wy = int(wy)
            peak, mo = peak_and_meltout(trace)
            if peak is None:
                continue
            per_wy.setdefault(wy, {"oni_ndj": winter_oni(rows, wy)})
            per_wy[wy].setdefault("peak_swe_in", {})[triplet] = round(peak, 1)
            if mo is not None:
                per_wy[wy].setdefault("melt_out_doy", {})[triplet] = mo
        x = [(per_wy[wy]["oni_ndj"], per_wy[wy]["peak_swe_in"][triplet]) for wy in per_wy
             if triplet in per_wy[wy].get("peak_swe_in", {}) and per_wy[wy]["oni_ndj"] is not None]
        m = [(per_wy[wy]["oni_ndj"], per_wy[wy]["melt_out_doy"][triplet]) for wy in per_wy
             if triplet in per_wy[wy].get("melt_out_doy", {}) and per_wy[wy]["oni_ndj"] is not None]
        entry = {"name": names.get(triplet, triplet), "n_years": len(x)}
        if len(x) >= 10:
            rho, p = spearman([a for a, _ in x], [b for _, b in x])
            entry["peak_swe_vs_oni"] = {"spearman_rho": rho, "p_perm": p, "n": len(x)}
        if len(m) >= 10:
            rho, p = spearman([a for a, _ in m], [b for _, b in m])
            entry["melt_out_vs_oni"] = {"spearman_rho": rho, "p_perm": p, "n": len(m)}
        # phase means
        by_phase = {}
        for o, pk in x:
            by_phase.setdefault(phase(o), []).append(pk)
        entry["peak_swe_by_phase"] = {k: {"mean_in": round(sum(v) / len(v), 1), "n": len(v)} for k, v in by_phase.items()}
        stations_out[triplet] = entry

    reservoirs_out = {}
    for code, res in storage["reservoirs"].items():
        pairs = []
        for wy, trace in res["years"].items():
            vals = [v for v in trace if v is not None]
            if len(vals) < 200:
                continue
            wy = int(wy)
            o = winter_oni(rows, wy)
            per_wy.setdefault(wy, {"oni_ndj": o})
            per_wy[wy].setdefault("peak_storage_af", {})[code] = max(vals)
            if o is not None:
                pairs.append((o, max(vals)))
        entry = {"n_years": len(pairs)}
        if len(pairs) >= 10:
            rho, p = spearman([a for a, _ in pairs], [b for _, b in pairs])
            entry["peak_storage_vs_oni"] = {"spearman_rho": rho, "p_perm": p, "n": len(pairs)}
        reservoirs_out[code] = entry

    for wy in per_wy:
        per_wy[wy]["phase"] = phase(per_wy[wy]["oni_ndj"])

    # Basin-mean peak SWE across all mapped pillows with data (>= 3 stations) for the headline test
    headline = []
    for wy, d in per_wy.items():
        pk = d.get("peak_swe_in", {})
        if len(pk) >= 3 and d["oni_ndj"] is not None:
            headline.append((d["oni_ndj"], sum(pk.values()) / len(pk), wy))
    hl = {}
    if len(headline) >= 10:
        rho, p = spearman([a for a, _, _ in headline], [b for _, b, _ in headline])
        hl = {"spearman_rho": rho, "p_perm": p, "n": len(headline),
              "what": "Nov-Jan mean ONI vs mean peak SWE across mapped SNOTEL pillows with data that year"}
        byp = {}
        for o, pk, wy in headline:
            byp.setdefault(phase(o), []).append(pk)
        hl["peak_swe_by_phase"] = {k: {"mean_in": round(sum(v) / len(v), 1), "n": len(v)} for k, v in byp.items()}

    out = {
        "_comment": "Generated by fetch_oni.py. ENSO context joined to the committed SNOTEL and storage histories. Do not edit.",
        "terms": ("Derived from public NOAA/NRCS/DWR records alongside Denver Water Design Storm data; Denver Water's "
                  "data terms travel with it (TERMS.md in this folder). Readings are provisional."),
        "oni_season": "Nov-Dec-Jan mean, the ENSO state when the snowpack is being laid down",
        "phase_thresholds": {"el_nino": 0.5, "la_nina": -0.5},
        "headline": hl,
        "stations": stations_out,
        "reservoirs": reservoirs_out,
        "water_years": {str(k): v for k, v in sorted(per_wy.items())},
        "general_knowledge": [
            "ENSO shifts the winter storm track; central Colorado lies between the El Nino-wet southern Rockies and the La Nina-wet northern Rockies, so its signal is weak and inconsistent (NOAA CPC teleconnection summaries).",
            "ENSO is a seasonal-scale predictor at best: it can tilt the odds on total snowpack, not on what arrives at a plant in 12 hours.",
        ],
        "honesty": "Correlations below are what the committed records show; n is small (one value per water year) and the permutation p-values are two-sided.",
    }
    with open(os.path.join(SIM, "enso-context.json"), "w") as fh:
        json.dump(out, fh, separators=(",", ":"))
    print(f"wrote sim-data/oni.json and sim-data/enso-context.json; headline {hl}")


if __name__ == "__main__":
    main()
