#!/usr/bin/env python3
"""One-time fetch of 15-minute USGS records around the biggest storms. Network.

For every event in ../explainable-viz/viz-data/storms.json (the top NOAA
precipitation days) plus the largest daily-turbidity days in the committed
record, pulls the USGS instantaneous-values service for a window from one
day before to five days after: discharge and gage height at Trumbull
(06701900) and turbidity, specific conductance and gage height at the
sentinel gage above Strontia Springs (06707525). Writes
sim-data/storm-windows.json. analysis/01_travel_time.py cross-correlates
these to estimate the Trumbull-to-Strontia travel time empirically, the
check on the Manning estimate in channels.json.

    python3 fetch_storm_windows.py

Rerun rarely; USGS revises instantaneous values after review (provisional).
Sites 06707500 and 06707000 have no instantaneous record on the service and
are not requested.
"""

import json
import os
import sys
import urllib.request
from datetime import date, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
VIZ = os.path.join(HERE, "..", "explainable-viz", "viz-data")
OUT = os.path.join(HERE, "sim-data", "storm-windows.json")

SITES = "06701900,06707525"
PARAMS = "00060,00065,63680,00095"
URL = ("https://nwis.waterservices.usgs.gov/nwis/iv/?format=json&sites={sites}"
       "&parameterCd={params}&startDT={start}T00:00-06:00&endDT={end}T00:00-06:00")
BEFORE, AFTER = 1, 5
N_TURB = 5

LABELS = {"00060": "discharge_cfs", "00065": "gage_height_ft", "63680": "turbidity_fnu", "00095": "spec_cond_uscm"}


def fetch(start, end):
    req = urllib.request.Request(URL.format(sites=SITES, params=PARAMS, start=start, end=end),
                                 headers={"User-Agent": "design-storm-2026 fetch_storm_windows"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.load(r)


def main():
    storms = json.load(open(os.path.join(VIZ, "storms.json")))
    daily = json.load(open(os.path.join(VIZ, "daily-series.json")))
    events = [{"date": e["date"], "why": f"NOAA precip {e['prcp_in']} in", "prcp_in": e["prcp_in"]}
              for e in storms["events"]]
    events.append({"date": storms["reference_storm"]["date"], "why": "Aug 14-15 2026 monsoon storm (committed replay)"})
    turb = daily["series"]["turb"]
    top = sorted((v, i) for i, v in enumerate(turb) if v is not None)[-N_TURB:]
    for v, i in top:
        d = daily["dates"][i]
        if d not in {e["date"] for e in events}:
            events.append({"date": d, "why": f"daily turbidity median {v} FNU", "turb_fnu": v})
    events.sort(key=lambda e: e["date"])

    windows = []
    for e in events:
        d0 = date.fromisoformat(e["date"])
        start, end = (d0 - timedelta(days=BEFORE)).isoformat(), (d0 + timedelta(days=AFTER)).isoformat()
        print(f"fetching {start}..{end} ({e['why']})", file=sys.stderr)
        try:
            data = fetch(start, end)
        except Exception as exc:
            print(f"  failed: {exc}", file=sys.stderr)
            continue
        series = {}
        for ts in data["value"]["timeSeries"]:
            site = ts["sourceInfo"]["siteCode"][0]["value"]
            code = ts["variable"]["variableCode"][0]["value"]
            vals = []
            for blk in ts["values"]:
                for v in blk["value"]:
                    if v["value"] in (None, "", "-999999"):
                        continue
                    vals.append([v["dateTime"][:16], float(v["value"])])
            if vals:
                series[f"{site}:{LABELS.get(code, code)}"] = vals
        windows.append({**e, "start": start, "end": end, "series": series,
                        "n_points": {k: len(v) for k, v in series.items()}})

    out = {
        "_comment": "Generated by fetch_storm_windows.py from the USGS instantaneous-values service. Do not edit.",
        "terms": ("USGS provisional data, subject to revision. Selected around Denver Water Design Storm events; "
                  "Denver Water's data terms travel with anything derived from it (TERMS.md in this folder)."),
        "fetched": date.today().isoformat(),
        "sites": {"06701900": "South Platte River near Trumbull (flow gauge, 27.6 km upstream of the sentinel)",
                  "06707525": "South Platte River above Strontia Springs Reservoir (sentinel water-quality gauge)"},
        "window_days": {"before": BEFORE, "after": AFTER},
        "time_note": "Timestamps are local (America/Denver) as served, truncated to the minute.",
        "windows": windows,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        json.dump(out, fh, separators=(",", ":"))
    print(f"wrote {os.path.relpath(OUT, HERE)}: {len(windows)} windows, {os.path.getsize(OUT) // 1024} KB")


if __name__ == "__main__":
    main()
