#!/usr/bin/env python3
"""One-time fetch of daily outlet-gage flow for the sub-basin views. Network.

The committed CSVs cover only the sentinel mainstem (DWR PLASPLCO). The
sub-basin behaviour board and the 3D water-year replay also want the west-slope
and nested outlet hydrographs, so this fetches daily mean discharge (USGS
parameter 00060, statistic 00003) for the four remaining basin outlet gages
from the USGS daily-values API and folds it per water year, the same shape as
water-system-3d/storage-history.json.

    python3 fetch_basin_flows.py            # writes viz-data/basin-flows.json

Rerun rarely: the history barely changes and every reading is provisional
until USGS review. Both pages degrade gracefully when basin-flows.json is
absent (the views say the fetch has not been run instead of charting).
"""

import json
import os
import urllib.request
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "viz-data", "basin-flows.json")

GAGES = {
    "09050700": "Blue River below Dillon",
    "09023562": "Fraser River below Moffat Tunnel",
    "09037500": "Williams Fork near Parshall",
    "06701900": "South Platte near Trumbull",
}
START = "1980-10-01"
URL = ("https://waterservices.usgs.gov/nwis/dv/?format=json&sites={site}"
       "&parameterCd=00060&statCd=00003&startDT={start}&endDT={end}")


def water_year(day_iso):
    y, m = int(day_iso[:4]), int(day_iso[5:7])
    return y + 1 if m >= 10 else y


def day_of_water_year(day_iso):
    y, m, d = int(day_iso[:4]), int(day_iso[5:7]), int(day_iso[8:10])
    return (date(y, m, d) - date(y if m >= 10 else y - 1, 10, 1)).days


def fetch(site):
    url = URL.format(site=site, start=START, end=date.today().isoformat())
    with urllib.request.urlopen(url, timeout=120) as r:
        data = json.load(r)
    series = data["value"]["timeSeries"]
    if not series:
        return {}
    years = {}
    for row in series[0]["values"][0]["value"]:
        day = row["dateTime"][:10]
        value = float(row["value"])
        if value < 0:  # USGS missing-value sentinel
            continue
        wy = str(water_year(day))
        years.setdefault(wy, [None] * 366)[day_of_water_year(day)] = value
    return years


def median_trace(years):
    trace = []
    for doy in range(366):
        vals = sorted(v[doy] for v in years.values() if v[doy] is not None)
        if len(vals) < 2:
            trace.append(None)
            continue
        mid = len(vals) // 2
        trace.append(vals[mid] if len(vals) % 2
                     else round((vals[mid - 1] + vals[mid]) / 2, 2))
    return trace


def main():
    gages = {}
    for site, name in GAGES.items():
        print(f"fetching {site} ({name})...")
        years = fetch(site)
        gages[site] = {"name": name,
                       "years": dict(sorted(years.items())),
                       "median": median_trace(years)}
        print(f"  {len(years)} water years")
    payload = {
        "_comment": "Generated by fetch_basin_flows.py from the USGS "
                    "daily-values API. Daily mean discharge (00060/00003), "
                    "cfs, folded per water year (Oct 1 = day 0); median "
                    "across all fetched years. Provisional, subject to USGS "
                    "revision. Do not edit by hand.",
        "fetched": date.today().isoformat(),
        "gages": gages,
    }
    with open(OUT, "w") as f:
        json.dump(payload, f, separators=(",", ":"))
    print(f"wrote {OUT} ({os.path.getsize(OUT):,} bytes)")


if __name__ == "__main__":
    main()
